@baseUrl = http://localhost:3001/api/v2/users

@email = neeti@example.com
@password = password123

### Login success
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}
}

### Logout User
POST {{baseUrl}}/logout

### Check user's token
GET {{baseUrl}}/auth